### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [mock-server/mockserver#1004]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by jamesdbloom** [comment]
Please reach out to me on Slack.
I've also updated the GitHub vulnerability contact details.

**Comment by pwntester** [comment]
Thanks for updating the policy, it will become very handy for future reports!
I tried reaching out to you or other maintainers in the slack channel some months ago but, unfortunately, I didnt succeed.
Issue hit our disclosure deadline and was [published](https://securitylab.github.com/advisories/GHSL-2021-059-mockserver/) as a result of that. Let me know if we can be of any help remediating the vulnerability

**Comment by jamesdbloom** [comment]
Yes thanks I saw that.  Given this is a testing tool arbitrary code execution is by design a core feature.  So this CVE is odd in a sense but not wrong.  Effectively for people wanting to secure that they likely need to enable mTLS but the documentation around that could be improved.  In addition authentication could be enabled for administration endpoints so that only authenticated users could do arbitrary code execution.

I'm going to close this issue but create a feature request for authentication of the control plane endpoints and documentation of this CVE.
