### ISSUE TITLE
Newer JavaScript & JSON Schema

### ISSUE THREAD

**Issue by lmmarsano** [mock-server/mockserver#1016]
**Describe the feature request**
Could mockserver use libraries that support more current versions of JavaScript & JSON Schema?

nashorn only supports ECMAScript 5.1 from 2009.
[GraalJS](https://github.com/oracle/graaljs) supports the latest.

The library currently in use for JSON Schema
https://github.com/mock-server/mockserver/blob/33ce88631b4e3d09b499caccfe1f7897f9fc8f18/mockserver-core/pom.xml#L131-L132
[only supports draft 4](https://github.com/java-json-tools/json-schema-validator#relevant-documents) from 2013, which is 5 drafts ago.
Several other libraries

- https://github.com/ssilverman/snowy-json
- https://github.com/eclipse-vertx/vertx-json-schema
- https://github.com/networknt/json-schema-validator

do a better job of staying current.

**What you are trying to do**

- Use newer JavaScript features like arrow function and destructuring (eg, `request.body.map(({email}) => email)`) in response templates.
- Use `JSON_SCHEMA` body matcher: the `contains` keyword was unavailable, so I had to use another kind of body matcher.

**The solution you'd like**
Not sure of the best solution: don't know much Java.

**Comment by jamesdbloom** [comment]
The version of JSON Schema has been upgraded already and so now draft 4, 6, 7 and 2019-09 is supported with 7 being the default.

On the topic of better JS support I agree that would be great.  Currently GraalVM only works as a third party library on Java 11+ and MockServer relies on Java 8 because currently that is still the most popular solution.

I'm happy to test the use of the JS templating on GraalVM to test how it works as it is supposed to a drop in replacement.  If that works I could provide some documentation on how to do that.  That would mean you'd need to run MockServer using the GraalVM.  A docker container could also be created to support that.  The only issue I believe is that GraalVM may need a license.

**Comment by jamesdbloom** [comment]
Moving this to backlog.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/NFWWW7lI/161-investigate-support-for-graalvm-or-modern-js-engine

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
