### ISSUE TITLE
How to upsert an expectation with an object callback?

### ISSUE THREAD

**Issue by andre-aktivconsultancy** [mock-server/mockserver#1037]
I feel like I must be missing something obvious but can't seem to figure this one out.

For this project I am writing an http mock with mock-server using upsert so that during the runtime of mock I can change the behavior by upserting an expectation.

So like this:
```
mock.upsert(
  new Expectation(request().withMethod("GET").withPath(MY_PATH))
    .thenRespond(response().withBody(json("{\"hello\": \"world\"}")))
    .withId(MY_REQUEST_ID));
```
Now I need some more dynamic behavior so I want to use a callback.

```
mock.when(request().withMethod("POST").withPath(MY_PATH))
  .respond(
    httpRequest -> {
      final var response = dynamicResponse();
      return response().withBody(json(response));
     });
```

Now I can not figure out how to combine the above, so that I have an expectation with a known id, that I can upsert. Expectation does have an `thenRespond` overload that takes an `HttpObjectCallback` which sounds like what I am after, but that needs a clientId which I don't no where to get from, or how to pass the actual callback.

Again it feels like I am missing something obvious. Any help is much appreciated.

**Comment by jamesdbloom** [comment]
I think this is not currently supported due to the use of WebSockets but this could be added.

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/cYE5ini1/175-upsert-an-expectation-with-an-object-callback

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
