### ISSUE TITLE
Project status (is this still actively maintained?)

### ISSUE THREAD

**Issue by OliverJAsh** [mock-server/mockserver#1039]
It seems there hasn't been much activity from maintainers recently. Is this project still actively maintained, or do you now recommend using a different tool?

**Comment by Arkinator** [comment]
Wiremock does much of the same stuff. For my exact case Mockserver is simply better, so I'm sticking around. In the past there were multiple dead-times from @jamesdbloom , so I'd guess this is temporary but will happen again in the future.

**Comment by slawekjaranowski** [comment]
Maybe other people can help with project maintenance ...

**Comment by brunopalos** [comment]
This is such a useful tool so I think it would be easy to find more maintainers. I'm willing to help.

**Comment by ChristianCiach** [comment]
The last commit was almost 9 months ago and almost all issues since then have no responses from any maintainer. PRs are piling up. 

I am not trying to be rude. It's just that our company disallows the usage of unmaintained libraries, so mockserver is close to being blacklisted, which would be a bummer.

**Comment by durcon** [comment]
@jamesdbloom 

I guess, you are not maintining the project anymore, right? No new version since 2023.

I ask, because if you can't maintain it and no one else can do it, I have unfortunately to plan a migration to [WireMock](https://github.com/wiremock/wiremock). I need the migration from `javax` to `jakarta`.
