### ISSUE TITLE
Accessing json request body parameters from velocity template

### ISSUE THREAD

**Issue by ailjushkin** [mock-server/mockserver#1052]
There is no feature to access json parameters when using velocity template, only $response.body object is avaliable, you can't do something like that:

your request body is:

```
{
  "accountNumber": "1111"
}
```

your velocity template is:

```
{
  "clientNumber": "$request.body.accountNumber"
}
```

I also found that there is jsonTool at velocity tools: https://velocity.apache.org/tools/devel/tools-summary.html#JsonTool

<html>
<body>

Json tool method | Description
-- | --
$json.parse(JSON content) | Parse JSON content
$json.read(resource) | Parse the content of a local resource
$json.fetch(URL) | Parse the content of a distant resource
$json.root() | Returns the root parsed JSON object or array
$json.get(index or property) | Returns the value under the specified index (for an array) or named property (for a map), if present, or null

</body>
</html>

But I have no luck trying to use that, seesm like you have to explicitly add this dependency to your build.

**Comment by lokendramani** [comment]
Same feature I want to in one of my requirement, please suggest a way below is my request:
{
    "id": "654b7ff0-f723-4942-9803-6bbc1b74dee6",
    "name": "someName",
    "value": "someValue"
}

I want name should be include in my response:
{
"name": "someName",
}

I am able to to get request.body.json but after that I am unable to get hold of any field, please suggest.

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/eENvenAJ/174-access-json-request-body-parameters-from-velocity-template

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by jamesdbloom** [comment]
This has now been fixed in is being released which will be ready in the next few hours
