### ISSUE TITLE
mockserver.initializationJsonPath should support multi json files

### ISSUE THREAD

**Issue by jiweizhu** [mock-server/mockserver#1061]
**Describe the feature request**
config: mockserver.initializationJsonPath can support more than one json file. 

**What you are trying to do**
config: mockserver.initializationJsonPath can support more than one json file. 
Like: mockserver.initializationJsonPath=/abc/a.json;/abc/b.json.
So this makes lots of mock json data more easy to manage. 

**The solution you'd like**
config: mockserver.initializationJsonPath can support more than one json file. 
Like: mockserver.initializationJsonPath=/abc/a.json;/abc/b.json.

**Describe alternatives you've considered**
No other considerations.

**Comment by jamesdbloom** [comment]
This is already on the backlog and is expected to be added in the new release likely in the next few weeks or so.

See: https://trello.com/c/y6QoKIWH/118-support-multiple-initialisation-json-files

Closing this here as this feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed.

**Comment by jamesdbloom** [comment]
https://mock-server.com/mock_server/initializing_expectations.html#expectation_initializer_json_glob_patterns
