### ISSUE TITLE
Netty Vulnerablity 

### ISSUE THREAD

**Issue by JonathanAaron** [mock-server/mockserver#1114]
**Describe the issue**
Security Vulnerability with mockserver-client-java transient dependency netty. https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-43797

**What you are trying to do**
Netty transient dependencies should be updated.

**MockServer version**
5.10 - 5.11.2

**To Reproduce**
You would need to run this through a static code analysis that scans for vulnerabilities or take a deep dive into dependency tree.

1. How you are running MockServer - Testcontainers
2. Code you used to create expectations - scan of the package itself
3. What error you saw
https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-43797
**Expected behaviour**
What you expected to happen

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by jamesdbloom** [comment]
Please upgrade to a more recent version of MockServer such as 5.11.9, old versions will not be updated.

**Comment by crazyrokr** [comment]
Hello @jamesdbloom. README.md says 5.11.2 is the latest version. Also Maven shows 5.11.2 as the latest one. Where can 5.11.9 version be obtained from?

**Comment by jamesdbloom** [comment]
Sorry I mean 5.11.2 that was a typo, I think that previous comment was against the wrong issue.

Anyway I'm using the latest version of Netty available.  I think it would be worth understanding the context of this CVE as per good security practise.  Who and why is there a concern about this CVE?  Is MockServer a testing tool being used in production and what risk does this CVE actually pose?  It is important to understand the full context before making an assessment on CVEs otherwise security because a point scoring activity that is not related to actually increasing security but instead aiming at getting a scanning tool to give a higher score.  MockServer is not designed to be accepting sensitive production traffic but it is designed as a security tool.
