### ISSUE TITLE
Response body validation based on OpenAPI

### ISSUE THREAD

**Issue by jianziqin** [mock-server/mockserver#1147]
**Describe the feature request**
As API's schema is defined in openAPI doc. if the schema of response body changes and mockserver still uses the old schema of response body, that means the mock data are not immediately auto-detected the latest requirements of the API definition which will cause consumer and provider to be not on the same page. So openAPI doc is the baseline of a valid response mock data. 

**The solution you'd like**
if there is an optional parameter to control enabling response body's validation, that will be exactly helpful.

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/8izEHnYR/163-response-body-validation-based-on-openapi

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by brcros** [comment]
Hello, we are also looking for validation of expectation using openapi doc( request & response).
Actually, we use mockserver with a test framework, and so, we want tests to be not passed when api specifications does not match anymore with the mocks.
That would be a great feature to have the openapi extra validation.

**Comment by brcros** [comment]
Would this features be cover by this one ? 
https://github.com/mock-server/mockserver/issues/1239
