### ISSUE TITLE
Extend Documentation

### ISSUE THREAD

**Issue by jamesdbloom** [mock-server/mockserver#115]
1. add example of matching a JSON array (in request matcher examples)
1. CA certs, SSL & TLS (add page)
   - customise private key and x509
   - explain how the CA & TLS works
   - document adding MockServer CA certification as trusted cert to 
       - android emulator
       - mac os
       - Java JVM
   - add: `HttpsURLConnection.setDefaultSSLSocketFactory(SSLFactory.getInstance().sslContext().getSocketFactory());`

**Comment by jamesdbloom** [comment]
+ proxy notes for record & replay (to ease creation of expectations)
+ running from command line using maven plugin directly without a pom.xml
+ proxy client configuration for new client examples

**Comment by jamesdbloom** [comment]
SNAPSHOT download configuration

**Comment by jamesdbloom** [comment]
for SNAPSHOT see #138

**Comment by jamesdbloom** [comment]
homebrew formula

**Comment by jamesdbloom** [comment]
test paralysation / separate using query parameter and `Referer` header

**Comment by jamesdbloom** [comment]
add HTTP API

**Comment by poohsen** [comment]
if using the API is really the recommended way of setting up expectations (over, say, the Java client), then may I suggest that on this page here: http://www.mock-server.com/mock_server/creating_expectations.html, you remove the client sections, since they are already detailed in http://www.mock-server.com/mock_server/mockserver_clients.html? 

I actually didn't see the request matcher API description at first because the client stuff is very prominent. I was lucky that I read this part on the page about clients:

**Comment by jamesdbloom** [comment]
see #172 for more details documentation changes

**Comment by poohsen** [comment]
btw, I ended up using the java client instead of the API directly. I tried to deduce what the API calls would have to look like from the code and the logging but I had trouble with more complicated payloads (possibly escaping quotes and such) so I resorted to using the client. AFAICT there's no single page in the docs dedicated to explaining the actual JSON that needs to be sent to the server. Am I missing something?

**Comment by jamesdbloom** [comment]
You are absolutely correct, creating detailed API documentation is on the list for documentation improvements.

**Comment by jamesdbloom** [comment]
Add useful tip about: 

`HttpsURLConnection.setDefaultSSLSocketFactory(SSLFactory.getInstance().sslContext().getSocketFactory());`

From #205

**Comment by djoelz** [comment]
Hi @jamesdbloom! I've tried the latest version with the command line version of mock server and I get the certificate_unknown exception for https requests. Is creating my own java program the suggested work around for this issue?
Is there an example of how to do this with a simple endpoint to capture https traffic?

Thanks!

**Comment by alshari86** [comment]
@jamesdbloom 
Didn't see update on this issue.
We also wonder if we run a stand-alone MockServer, how do we setup the request/response expectation?
In our automation script, we have expectation setup for each request, then run MockServer during automation running.
But what if we want to run a stand-alone MockServer?
from the document, it just tells us how to run it, but didn't mention anything about setting up the response/request, where to set it up?

**Comment by jamesdbloom** [comment]
This is now the highest priority issue, after having fixed numerous other bugs.  Once I have completed one more release (in the next day or two) I will start to improve the documentation and fix no other bugs until it is done.

**Comment by jamesdbloom** [comment]
#257 document the harmonised MockServer and Proxy features.

**Comment by jamesdbloom** [comment]
#637 make "2. Run Test Scenarios" clearer that this refers to a user running their own tests

**Comment by jamesdbloom** [comment]
This has now been completed with the remaining two areas being migrated to the backlog as: https://trello.com/c/aZJt3YJA/57-improve-tls-documentation and https://trello.com/c/7HWvKoVR/55-document-ui
