### ISSUE TITLE
Mockserver critical vulnerabilities

### ISSUE THREAD

**Issue by adeete-zeotap** [mock-server/mockserver#1197]
**Describe the issue**
The docker image: mockserver/mockserver:latest appears to be vulnerable

**What you are trying to do**
Have a secure mockserver

**MockServer version**
Latest(5.12.0)

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc): Docker
2. Code you used to create expectations 
```[
  {
    "httpRequest": {
      "method": "GET",
      "path": "/mock"
    },
    "httpResponse": {
      "statusCode": 200,
      "body": "Successful response"
    }
  }]
```

```version: "3.8"
services:
  unity-mock-server:
    image: mockserver/mockserver:mockserver-snapshot
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: .
        target: /config
```

```
FROM mockserver/mockserver:mockserver-snapshot

WORKDIR /config
COPY mockserver.properties initializerJson.json /config/

ENV MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
ENV MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json

CMD []
```
3. What error you saw

<img width="966" alt="Screenshot 2022-02-24 at 11 25 20 AM" src="https://user-images.githubusercontent.com/87293273/155466476-2fbab9ef-fed5-454c-915a-021e1571e0e8.png">

**Expected behaviour**
What you expected to happen

No vulnerability

**Comment by jamesdbloom** [comment]
The MockServer image is based on the latest version of distroless which is a secure container without any OS or binaries other than the minimum to run the JVM.  The CVEs you point out not practical to implement because you would need to get the JVM to do this which as I understand is not possible.

Please remember CVEs are not the only measure of security.  They need to be taken in context especially as CVEs are often highlighted in code that is never executed as in this case.
