### ISSUE TITLE
Expectations with random or incremental responses?

### ISSUE THREAD

**Issue by evbo** [mock-server/mockserver#1230]
**Describe the feature request**
I want the same endpoint to return data differently each time it responds. 

**What you are trying to do**
I want to simulate a CRUD database by reflecting changes made each time the client sends requests. This is especially useful for UI dev work so that you see the UI react to different responses from the mock server. 

**The solution you'd like**
This could be achieved by applying a list of responses, whereby each time the mock endpoint expectation is accessed, the next response in the list is returned. To start from the beginning again, restart the mock server, or the list could cycle back to the beginning after all iterations are complete.

**Describe alternatives you've considered**
Setting dev environment env vars or settings in my app whereby special query parameters are added to the request, triggering a different expectation. However, it's dangerous having code like this that might get accidentally activated in production.

**Comment by jamesdbloom** [comment]
It is possible to return "random" or "rotating" responses currently. 

To return a response with random data you could use a response template with random data see: https://mock-server.com/mock_server/response_templates.html, alternatively you could use a method callback: https://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback or a class callback: https://mock-server.com/mock_server/creating_expectations.html#button_response_class_callback

To implement rotating responses use a callback see links above.  If you set each expectation as only applying once using `times` (see: https://mock-server.com/mock_server/creating_expectations.html#button_match_request_by_path_exactly_twice) then inside the callback create the same expectation again using a MockServerClient this will cause all the expectation you've set at the beginning to rotate.  This works because each expectation only applies once, but when the callback is executed for the expectation another identical expectation is created and added to the back of the list of expectations.

Also, I am planning to add support for more response flexibility to expectations including multiple responses, rotating responses or dropping response in the next few months.

**Comment by evbo** [comment]
> Also, I am planning to add support for more response flexibility to expectations including multiple responses, rotating responses or dropping response in the next few months.

@jamesdbloom will this be implemented for the JSON expectation initializer?

Something I forgot to clarify is I am only using the standalone jar - not the java API, so unfortunately none of your workarounds would apply for me. But if you are implementing those features for the initializer please confirm as that definitely sounds like it solves my problem.

Thanks for such a great library

**Comment by AdnanAliArshadtx** [comment]
@jamesdbloom any update on your last message?

**Comment by jamesdbloom** [comment]
This is now supported via #2180. You can provide a list of responses that cycle through sequentially:

```json
{
  "httpRequest": { "path": "/api/data" },
  "httpResponse": [
    { "statusCode": 200, "body": "{\"items\": []}" },
    { "statusCode": 200, "body": "{\"items\": [\"new-item\"]}" },
    { "statusCode": 200, "body": "{\"items\": [\"new-item\", \"another-item\"]}" }
  ]
}
```

When all responses are exhausted, the last one repeats.
