### ISSUE TITLE
Allow using specific examples when multiple examples are in OpenAPI spec

### ISSUE THREAD

**Issue by nayyara-cropsey** [mock-server/mockserver#1238]
# Feature
Currently, mock server will serve the first example when there are multiple examples in OpenAPI spec.
Consider allowing user to pick which example to serve.

# Suggestion
```
{
    "specUrlOrPayload": "https://raw.githubusercontent.com/mock-server/mockserver/master/mockserver-integration-testing/src/main/resources/org/mockserver/openapi/openapi_petstore_example.json",
    "operationsAndResponses": {
        "showPetById": "200",
        "createPets": "500"
    },
    "responsesAndExamples": {
        "showPetById":  "Dog" // assuming there is an example called "Dog"
    }
}
```

Honestly haven't put much thought into it - but this is a suggestion. Alternatively allow using headers to pick response

## Examples OAS

```yaml
responses:
  '200':
    description: A user object.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/User'   # Reference to an object
        examples:
          Jessica:
            value:
              id: 10
              name: Jessica Smith
          Ron:
            value:
              id: 20
              name: Ron Stewart
```

**Comment by jamesdbloom** [comment]
I agree that makes sense, and is now fairly high on the backlog and so will likely be implemented in the next month or so.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/PBaGSu6l/186-support-specifying-examples-when-multiple-examples-are-in-openapi-spec

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

This is going to be in the next release likely in the next month
