### ISSUE TITLE
Consider adding an OpenAPI validation proxy for API contract validation

### ISSUE THREAD

**Issue by nayyara-cropsey** [mock-server/mockserver#1239]
Similar to Prism: https://meta.stoplight.io/docs/prism/ZG9jOjYx-overview#-roadmap

**Comment by jamesdbloom** [comment]
I agree that makes sense, and is now fairly high on the backlog and so will likely be implemented in the next month or so.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/uwyag6az/185-openapi-validation-proxy-request-response

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by nayyara-cropsey** [comment]
Thank you @jamesdbloom!
