### ISSUE TITLE
Support yaml OpenAPI definition via REST API

### ISSUE THREAD

**Issue by rjacobs91** [mock-server/mockserver#1243]
**Describe the feature request**
Be able to support the creation of expectations from a YAML OpenAPI definition

**What you are trying to do**

- I want to setup my local application with local dependencies, of which include REST services
- I am using Docker Compose to do this as have AWS and other dependencies
- Currently my OpenAPI templates are in yaml rather than JSON and thus I can't use simple CLI tools like cURL to import the definition

**The solution you'd like**

- I should be able to import either type of definition using any of the APIs
- (Ideally as well I should be able to provide some kind of auth header/command for REST or file based access in order to access definitions remotely that require auth)

**Describe alternatives you've considered**

- Converting current files to JSON type is not practical so discounted

**Comment by jamesdbloom** [comment]
Thank you this was already on the backlog as it does make sense to support this, see: https://trello.com/c/YYrz6irR/180-support-yaml-on-api-for-openapi-expectation-creation-and-json-object-as-field

New features are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed.  However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
