### ISSUE TITLE
Support Json placeholders for headers as well

### ISSUE THREAD

**Issue by vbhosle** [mock-server/mockserver#1248]
Currently json place holders are supported only for matching body fields. 
https://www.mock-server.com/mock_server/creating_expectations.html#button_match_request_by_body_with_json_placeholders

Similar is expected for header matching

**Comment by jamesdbloom** [comment]
I don't understand what you are asking as MockServer doesn't support matching headers with JSON.

**Comment by vbhosle** [comment]
It does match headers from an initializer json file. 
If expected header doesn't match you will see a debug log, header didn't match
A small test to demonstrate

https://github.com/vbhosle/mockserver/commit/b20bcda5f87e76097b14f6a930b434986757c11d

**Comment by jamesdbloom** [comment]
This is not support because JSON matchers are not used for headers and adding such support is a big implemented.  Instead you can achieve the same using either a schema header matcher: https://www.mock-server.com/mock_server/creating_expectations.html#button_match_request_by_header_value_json_schema or using a regex header matcher: https://www.mock-server.com/mock_server/creating_expectations.html#button_match_request_by_header_value_regex

Also see: https://www.mock-server.com/mock_server/creating_expectations.html#request_property_matchers
