### ISSUE TITLE
Ability to include external text file in expectation.

### ISSUE THREAD

**Issue by senyor** [mock-server/mockserver#1257]
Current implementation allows static body inclusion. We need to include big external files such as XMLs for SOAP services.

To include external file into expectation response body.

It can be achieved by adding `"external": true` flag into `"httpResponse"` element. And reuse `"body"` with a URI-like style `file://external.xml`. THe same can be applied to template bodies. Need to correct json schema as well.

(1) I've tried to use a JavaScript template to load file there, but it hasn't worked. Nashorn engine has some limitations. (2) I haven't tried inclusion of external Java class for that purpose but it seems to be clumsy and unpractical.

**Comment by jamesdbloom** [comment]
I agree that makes sense, and is now fairly high on the backlog and so will likely be implemented in the next 1-2 months.

I can add support for both request and response bodies to be specified using a path that will check both the file system and the classpath.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/67FmFwyv/189-request-and-response-body-from-file-path

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
