### ISSUE TITLE
Exclude conflicting versions

### ISSUE THREAD

**Issue by hetzijzo** [mock-server/mockserver#1276]
Recently another version conflict was resolved by specifying the versions of `commons-beanutils` and `commons-logging` in the root pom. It solves the problem partly, only the new version is specified where I expect the conflicting versions to be excluded. Projects can have the `maven-enforcer-plugin` in place, which can cause a problem with these conflicting dependencies.

I expect the conflicting dependencies not to be available as transitive dependencies. Like `mockserver -> velocity-tools-generic -> commons-beanutils` should be excluded.

**Comment by jamesdbloom** [comment]
commons-beanutils is only pulled in transitively by two libraries velocity-tools-generic and commons-digester3 excluding the dependency is inherently flaky because if either dependency stops using commons-beanutils and the other is excluding it the code will fail in a way that is non-obvious.

forcing the version of the dependency however is the ideal situation because this is inherently not-flaky and in addition will allow this dependency to be updated if a vulnerability is found in a specific version.
