### ISSUE TITLE
Ingress with k8s v1.22+

### ISSUE THREAD

**Issue by xxcite** [mock-server/mockserver#1409]
**Describe the issue**
With Kubernetes versions >= v1.22 the `extensions/v1beta1` API version of Ingress is no longer served, see [Deprectaion Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122). In the current released [Helm Ingress Template](https://github.com/mock-server/mockserver/blob/mockserver-5.13.2/helm/mockserver/templates/ingress.yaml#L5) this API version is still used. With `ingress.enabled: true` the Helm installation fails.

**What you are trying to do**
Install Mockserver with Helm chart.

**MockServer version**
5.13.2

**To Reproduce**
Set `ingress.enabled: true` and install using Helm chart 5.13.2 in Kubernetes with version >= v1.22

**Expected behaviour**
Even with `ingress.enabled: true` the Helm installation is successful

**MockServer Log**
N/A

**Comment by alexanderccc** [comment]
This seems to have been fixed in April but nobody bothered to build/validate the new chart version? https://github.com/mock-server/mockserver/commit/6f48421994b36eac6475f2a482842c179b0f8f2c#diff-573faa656a1d28aedb7d58b1443378b98c1266d87cdf697ded5036a98f85bfbd 

I'm also having issues with this, can someone release a new version of the chart with the updated Ingress?

**Comment by jamesdbloom** [comment]
Closing as already fixed a new release will happen in the next week or so
