### ISSUE TITLE
Incompatible client/server versions

### ISSUE THREAD

**Issue by dnsbtchr** [mock-server/mockserver#1449]
**Describe the issue**
After updating to the latest (5.14.0) version of mockserver-client-java, I get 
`org.mockserver.client.ClientException: Client version "5.14.0" major and minor versions do not match server version "5.13.2"`.
I thought that to fix this it's as simple as updating the server as well but on Dockerhub the latest version is still 5.13.2. Is there another way to fix this or will there be an update of the server soon as well?

**What you are trying to do**
Verifying HTTP calls

**MockServer version**
Client: 5.13.2
Server: 5.14.0

**To Reproduce**
Just use it in any way

**Expected behaviour**
Either backwards compatibility or an updated server

**Comment by jamesdbloom** [comment]
Please see link to the latest version that is already on docker hub: https://hub.docker.com/layers/mockserver/mockserver/mockserver/5.14.0/images/sha256-387605f22ffe3f3d7f51acba48ff8adf81260026421e8f65b2624aa611977f81?context=explore

**Comment by dnsbtchr** [comment]
Thanks. I don't know what I did earlier but I didn't find that version. Got it now. Amazing that you answered so fast!

**Comment by tmueller64** [comment]
Is there any intention to support the client and server being different versions? If this is already supported, when did it start? We are currently on 5.12 and would like to move to a more recent version but this is difficult when we have to change both the client and server at the same time for all repos. We have every repo that exports a REST API also provide a set of expectations to mock that API so that repos that use that API can use mockserver. Thanks.
