### ISSUE TITLE
Dashboard not available when Mock-Server is started on port different to 1080

### ISSUE THREAD

**Issue by ThiAmm** [mock-server/mockserver#1456]
**Describe the issue**
If i start mock-server with `ClientAndServer.startClientAndServer(1080);`, then the dashboard is available at http://localhost:1080/mockserver/dashboard. But if i start mock-server `ClientAndServer.startClientAndServer(6000)`, then the dashboard is not available at
http://localhost:6000/mockserver/dashboard.
**What you are trying to do**
I am trying to view the dashboard. 
**MockServer version**
```
	<dependency>
		<groupId>org.mock-server</groupId>
		<artifactId>mockserver-netty</artifactId>
		<version>5.14.0</version>
	</dependency>
```

**To Reproduce**

1. How you are running MockServer (i.e maven plugin, docker, etc): Using JAVA API
2. Code you used to create expectations
3. What error you saw

**Expected behaviour**
Get the dashboard via url `http://localhost:6000/mockserver/dashboard`

**Comment by jamesdbloom** [comment]
This is because Chrome considers 6000 as an unsafe port used for X11 so it blocks it, this is not related to MockServer.  Try using a different port and you will find it works correctly.  

For more information see: https://medium.com/@msinha2801/why-are-some-ports-considered-unsafe-restricted-c3c22d0596c0
