### ISSUE TITLE
Java client v5.14 doesn't verify correct calls anymore?

### ISSUE THREAD

**Issue by mamuf** [mock-server/mockserver#1457]
Hi, I've updated the MockServer Java client to 5.14 and my tests suddenly fail? I use the Spring Boot Test integration and now I get this:

```
2022-08-29 17:19:33.255 DEBUG 19928 --- [           main] c.w.f.f.ExchangeRatesService   : HTTP GET with date='08.09.2021' to http://localhost:64605/rates

java.lang.AssertionError: Request not found exactly once, expected:<{
  "path" : "/rates"
}> but was:<{
  "headers" : {
    "content-length" : [ "0" ],
    "Accept" : [ "text/plain" ],
    "Cache-Control" : [ "no-store" ],
    "content-encoding" : [ ".*" ],
    "host" : [ "localhost:64605" ],
    "User-Agent" : [ "dummy" ],
    "Referer" : [ "http://localhost:64605/rates" ],
    "accept-encoding" : [ "gzip" ]
  },
  "keepAlive" : true,
  "method" : "GET",
  "path" : "/rates",
  "queryStringParameters" : {
    "date" : [ "08.09.2021" ]
  },
  "secure" : false
}>
```

Note that I'm using Maven and Kotlin, but that shouldn't really matter.

This is the verify call that fails:

```
mockServerClient.verify(
    request()
        .withPath(exchangeRatePath)
        .withPathParameter("date", "10.09.2021"),
    once()
)
```

Interesting fact is that when I comment out either the `withPath`, or `withPathParameter`, it works! So why doesn't it work with more specific verification?

**Comment by jamesdbloom** [comment]
The verification you have provided doesn't look correct.  You are requesting path parameters but your expectation is setting query parameters.  That is why it is not matching.  A bug was fixed with path parameter matching during verifications in the latest version which explains why you bug in your verification request is not correctly not working.

Please change your verification requests to use query parameter instead of path parameter and your code should work as expected.

**Comment by mamuf** [comment]
Oh, that explains it, it works. Thanks!
