### ISSUE TITLE
Callback after HttpResponse with delay

### ISSUE THREAD

**Issue by mohammali** [mock-server/mockserver#598]
Hello, 

Is there way to add callback after sending the response with delay?

I like to have feature:

```
HttpResponse.response()
                    .withHeader("content-type", "application/json")
                    .withBody(body)
                    .withStatusCode(200)
                    .withDelay(TimeUnit.MILLISECONDS, 5000)
                    .withCallback((req, resp) -> {
                        /*Do some staff after mock server sending the response*/
                    });
```

Thank you for supporting.

**Comment by ArkadiyShuvaev** [comment]
Hi @mohammali, 
Have you found a solution?

Thank you.

**Comment by jamesdbloom** [comment]
It would be possible to add this although it is not straightforward.  Something similar could be achieved by using a callback to return a response and running a thread from the callback.

Can you please explain the requirements, what you are trying to achieve and why so that I can understand the problem better.

**Comment by mohammali** [comment]
We want to track the requests and the responses, my use case is when the mock server receives the request and sends the response to the client I want a callback to say:
I received this request and send this response.

**Comment by jamesdbloom** [comment]
The typical approach to achieve this is to use a method / closure callback action, as shown here: http://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback

I'll add another example to the website to make this clearer and add the link here.

It is also possible to do this using a class callback http://mock-server.com/mock_server/creating_expectations.html#button_response_class_callback this is less flexible because the class doesn't have access to local variables inside the test code.

**Comment by mohammali** [comment]
Maybe my explanation not full, I want the callback to invoke after the client receives the response and close the connection.

**Comment by jamesdbloom** [comment]
This seems to be related to #572

**Comment by jamesdbloom** [comment]
I will look to implement post action callbacks as either a websocket callback (i.e. closure) or a remote HTTP request (i.e. web hook) as one of the next new features.

**Comment by mohammali** [comment]
Fair enough, Thank you for hard-working.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/gvXf5Mcr/53-callback-after-expectation-action-completed

**Comment by jamesdbloom** [comment]
This is now supported via #2180 using the `afterActions` feature:

```json
{
  "httpRequest": { "path": "/api" },
  "httpResponse": {
    "statusCode": 200,
    "body": "response body",
    "delay": { "timeUnit": "MILLISECONDS", "value": 5000 }
  },
  "afterActions": [{
    "httpRequest": {
      "method": "POST",
      "path": "/callback-url"
    }
  }]
}
```

After-actions fire asynchronously after the primary response is sent.
