### ISSUE TITLE
Override a default response with a custom response on client side

### ISSUE THREAD

**Issue by kshrestha99** [mock-server/mockserver#657]
I would like to override an expectation that has already been set up. On https://github.com/jamesdbloom/mockserver/issues/280 you mentioned that it is not allowed by design. I have a need to do something like that, would you be open to changing it, and allow that if two expectations match then the one with the more specific matchers (say headers or something else) will be matched instead of the it always being the first one? @jamesbloomnektan

**Comment by jamesdbloom** [comment]
Can you please provide more background explaining the situation you are trying to support so that I can understand exactly what you are trying to do and why.  I may be able to make a suggestion as to how this can already be achieved with the existing features available.  Alternatively, I would then be able to understand what is missing so I can add it.

**Comment by jamesdbloom** [comment]
I think the following item on the backlog should provide what you need because it will support priorities for expectations.  So you will be able to add a higher priority expectation which will be matched in preference. 

See the backlog: https://trello.com/c/9G3Hkdu3/31-default-expectation-expectation-priority

**Comment by jamesdbloom** [comment]
I am currently adding support to update existing expectation by using its id as part of #653

**Comment by jamesdbloom** [comment]
I have now added support for expectation priority which can be used to change the matching order or expectations.  Now matching priority is considered first before the creation order. This means a default expectation can be created at any time by creating a new higher priority expectation that is guaranteed to be matched first (if its priority is higher then all other expectations)
