### ISSUE TITLE
How to record website using chrome and replay it using mockserver proxy

### ISSUE THREAD

**Issue by rajeevdave** [mock-server/mockserver#681]
We have installed mock server and mock proxy in unix server. Now I want to run web page using chrome browser and record. After recording, I would like to run it again through web browser.

I am not able to find step by step action anywhere.

Please help.

**Comment by jamesdbloom** [comment]
MockServer does not support completely automated record and replay because this is an anti-pattern that results in tests that break encapsulation and separation of concerns.  Such tests are very brittle and very expensive to maintain.  However, with MockServer it is possible to record expectations and then  use code to "replay" those expectations as described: http://mock-server.com/proxy/record_and_replay.html

For how to configure chrome also see: http://mock-server.com/proxy/configuring_sut.html
