### ISSUE TITLE
Keeping a changelog

### ISSUE THREAD

**Issue by pnsantos** [mock-server/mockserver#706]
**Describe the feature request**
Not sure if there is a list somewhere with the changelog. Git commits are somewhat difficult to parse (and distinguish the relevant from non-relevant from a user pov).
Would be a very useful addition to keep track of significant changes/fixes or new feature between versions.

**What you are trying to do**
\-

**The solution you'd like**
Something along the lines of this: https://keepachangelog.com/en/1.0.0/

**Describe alternatives you've considered**
\-

**Comment by jamesdbloom** [comment]
This is a good idea I will add it in the next release.

**Comment by jamesdbloom** [comment]
This is a high priority feature and will be worked on very soon but new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/HGGSSo1u/74-add-changelog
