### ISSUE TITLE
[Question] Issues when set up with Mozilla firefox

### ISSUE THREAD

**Issue by goncer** [mock-server/mockserver#709]
**Describe the issue**
I would like to use mockServer with the browser, so I can redirect some dependencies to a specific mock. But it looks like I have something wrong with certificates.

**What you are trying to do**
Adding as a proxy the mock server.

**MockServer version**
java -jar mockserver-netty-5.8.0-jar-with-dependencies.jar -serverPort 1234 -logLevel DEBUG

**To Reproduce**
Steps to reproduce the issue:

1. Run the mock server as specified above.
2. Setup the proxy manually. 
![image](https://user-images.githubusercontent.com/15139384/70980160-20d0a180-20b3-11ea-9891-6bc138cc0143.png)
3. Land to any url
![image](https://user-images.githubusercontent.com/15139384/70980127-0f879500-20b3-11ea-8318-25d9beaa6f71.png)

**Expected behaviour**
Being able to reach somewhere.

**MockServer Log**
Think is not neccesary.

**Comment by jamesdbloom** [comment]
If you add the MockServer Root CA as a trusted CA to your OS then this will improve the problem, but not solve it completely as described below.   I would not recommend doing this for longer than you absolutely need, and while this is trusted don't navigate to any sensitive sites like your bank or email.  That is because the private key for the MockServer Root CA is in this repository and therefore technically if you tell your OS to have a root of trust with that certificate someone may be able to pretend to be your bank by using the private key and doing a man-in-middle attack on you.  This is the same problem for all proxies that intercept TLS dynamically and there is no technical way to make this 100% secure.

In addition, there are two modern features of TLS / HTTP that may mean some sites (those with the best security, like google sites) still won't work.  This is because of [Certificate Transparency](https://tools.ietf.org/html/rfc6962) and [Public Key Pinning](https://tools.ietf.org/html/rfc7469), both of which make it hard to dynamically create a certificate that Chrome, Firefox or IE will trust as legitimate.

As I understand Firefox is the most likely browser to work best for this.

I am adding a new TLS page to the web site to explain this and other TLS related topics for MockServer, that page will appear shortly once I have done the next release.

**Comment by goncer** [comment]
Many thanks for the answer @jamesdbloom , It worked. 
Steps: 
* Download the CA certificate: 
wget https://raw.githubusercontent.com/mock-server/mockserver/master/mockserver-core/src/main/resources/org/mockserver/socket/CertificateAuthorityCertificate.pem
* Add certificate to the trusted authorities importing the .pem downloaded file.
![image](https://user-images.githubusercontent.com/15139384/71357354-b5d90c00-2585-11ea-8f7e-ec1e17223ffa.png)
* configure proxy.
![image](https://user-images.githubusercontent.com/15139384/71357399-f33d9980-2585-11ea-8fd0-e28c2cd5e0b2.png)

Now un-installing it to prevent the man in the middle. 
Br,
Gonzalo.
