### ISSUE TITLE
MockServerClient verify for the request body doesn't work

### ISSUE THREAD

**Issue by mardoz** [mock-server/mockserver#711]
This issue is to report that issue #601 is not resolved in the latest releases 8.5.1 or 8.5.2-SNAPSHOT despite it looking like the fixes were pushed to those versions.

I've forked the previous example and updated it to 8.5.2-SNAPSHOT to demonstrate: https://github.com/mardoz/mock-server-example

**Comment by jamesdbloom** [comment]
This bug was actually unrelated to #601 but it was unfortunately introduced when #601 was fixed.  The issue was caused by matching against an empty or null body always passing for the control plane, however, the matching should be identical between the control plane and normal matching for expectations.

Two of the unit tests were wrong and were asserting the wrong thing so it wasn't caught.  I've fixed the tests and the bug.  I have also added some more integration tests to mirror your example but with assertions.

I am just updating the SNAPSHOT version so that should have the bug fix in the next 10 mins.
