### ISSUE TITLE
httpOverrideForwardedRequest does not allow httpResponseTemplate

### ISSUE THREAD

**Issue by georgewilk01** [mock-server/mockserver#716]
Need to override header in response to forwarded request

I am forwarding a request using httpOverrideForwardedRequest and would like to override the response headers using template.

Ideally, I would create an expectation as follows
```javascript
{
    "httpRequest": {
        "path": "/some/path"
    },
    "httpOverrideForwardedRequest": {
        "httpRequest": {
            "socketAddress": {
                "host": "target.host.com",
                "port": 1234,
                "scheme": "HTTPS"
            }
        },
        "httpResponseTemplate": {
            "template": "return { statusCode: 200, headers: JSON.stringify({location: response.headers[\"location\"], body: response.body}) };",
            "templateType": "JAVASCRIPT"
        }
    }
}
```

I could not come up with a viable alternative.  Are there any?

**Comment by jamesdbloom** [comment]
Currently overriding the response is supported using
- a static override request & response: http://mock-server.com/mock_server/creating_expectations.html#button_forward_overridden_with_resp
- a dynamic class callback: http://mock-server.com/mock_server/creating_expectations.html#button_forward_class_callback
- a dynamic object / closure callback: http://mock-server.com/mock_server/creating_expectations.html#button_forward_method_or_closure_callback

I'm reluctant to add support for JavaScript templating because JavaScript rendering is now deprecated from the JVM, although still works (I've tested it) up to 12.  I could add this if I found a good alternative JavaScript renderer.

Do any of the 3 options above meet your needs?

**Comment by jamesdbloom** [comment]
Closing this issue as no response to the request for more information.
