### ISSUE TITLE
Add possibility to mock server side events (streams)

### ISSUE THREAD

**Issue by alessss** [mock-server/mockserver#730]
**Describe the feature request**
Please, add a possibility to mock server side events (https://www.w3.org/TR/eventsource/#reestablish-the-connection)

**What you are trying to do**
I'm writing tests for mobile app, and in one of app screens uses stream to get data from the server. I need a way to mock this request, and create fake stream from my mockserver instance.

**The solution you'd like**
Expectation should respond with a stream of some predefined data. 

If enough time for implementation - it would be nice to be able to set expectation with several pieces of data, which should be returned in some order or randomly by mockserver. Would be nice to see number of responses per second configurable.

**Comment by jamesdbloom** [comment]
there is already an item on the back for sever side events, please see: https://trello.com/c/VhZCtmAo/25-support-server-sent-events

new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed.
