### ISSUE TITLE
Failing to start only on Cloud Foundry - Error: spawn java ENOENT

### ISSUE THREAD

**Issue by antoni-g** [mock-server/mockserver#745]
**Describe the issue**
Trying to deploy to cloud foundry. Running fine as is on my local 

```16:00:26.913: [APP/PROC/WEB.0] Running 'java -Dfile.encoding=UTF-8 -jar node_modules/mockserver-node/mockserver-netty-5.9.0-jar-with-dependencies.jar -serverPort 8080 -logLevel DEBUG'
16:00:26.913: [APP/PROC/WEB.0] spawn called
16:00:26.917: [APP/PROC/WEB.0] [Arguments] {
16:00:26.917: [APP/PROC/WEB.0]   '0': 'java',
16:00:26.917: [APP/PROC/WEB.0]   '1':
16:00:26.917: [APP/PROC/WEB.0]    [ '-Dfile.encoding=UTF-8',
16:00:26.917: [APP/PROC/WEB.0]      '-jar',
16:00:26.917: [APP/PROC/WEB.0]      [ 'node_modules/mockserver-node/mockserver-netty-5.9.0-jar-with-dependencies.jar' ],
16:00:26.917: [APP/PROC/WEB.0]      '-serverPort',
16:00:26.917: [APP/PROC/WEB.0]      '8080',
16:00:26.917: [APP/PROC/WEB.0]      '-logLevel',
16:00:26.917: [APP/PROC/WEB.0]      'DEBUG' ],
16:00:26.917: [APP/PROC/WEB.0]   '2': { stdio: [ 'ignore', [Socket], [Socket] ] } }
16:00:26.931: [APP/PROC/WEB.0] Using port '8080' to stop MockServer and MockServer Proxy
16:00:26.951: [APP/PROC/WEB.0] Error: spawn java ENOENT
16:00:26.951: [APP/PROC/WEB.0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
16:00:26.951: [APP/PROC/WEB.0]     at onErrorNT (internal/child_process.js:415:16)
16:00:26.951: [APP/PROC/WEB.0]     at process._tickCallback (internal/process/next_tick.js:63:19)
16:00:26.951: [APP/PROC/WEB.0]     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
16:00:26.951: [APP/PROC/WEB.0]     at startup (internal/bootstrap/node.js:283:19)
16:00:26.951: [APP/PROC/WEB.0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
**What you are trying to do**
Deploying this application as a Node application to Cloud Foundry. Application is failing to start

**MockServer version**
5.9.0

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
Running on cloud foundry docker images with the nodeJS Buildpack

**Expected behaviour**
Application to start

**Comment by jamesdbloom** [comment]
I would suspect your node process does have the ability to run the java binary. This is likely because:
1. java is not installed
2. node does not have permission to execute the java process
3. java is not on the PATH for the node process so it can not execute the java binary without fully qualifying the path

None of these issues are something within the control of MockServer and is related to the environment where you are running your command i.e. Cloud Foundy.  However, this issue in the backlog will help: https://trello.com/c/faFiapID/96-binary-bundle-with-jvm-requirement-for-mockserver-node once this feature is completed `mockserver-node` will be fully self-contained and will not rely on any java installed by the OS.

I'm going to close this ticket as it is clear from the error log that this is extremely unlikely to be a bug in `mockserver-node`

**Comment by antoni-g** [comment]
Hi James - thanks. I suspected these may be these case myself (whittled it down to 2 or 3, unfortunately on CF don't have access to validate either within the box through spawn). Thanks for the update
