### ISSUE TITLE
maintain class expectation initializer expectations when also using json expectation initializer and file watcher

### ISSUE THREAD

**Issue by vin-vij** [mock-server/mockserver#751]
Sir,
Thanks for your great work. 
I have deployed the mockserver war in tomcat 9 and I have created a class in my application which implements the ExpectationInitializer.
I have also configured JSON file using the mockserver.properties
I have added a mockserver.properties file in resource folder of the war and the application works fine.
It matches the URLs from both the java file and the JSON file and renders response.

The issues is that, once I modify the JSON file, non of the values (path) from the java files get matched, I can still get the values from JSON file (modified)

I think, once the filewater updates the matcher, it  wipes out java paths ( expectations from java class) and keeps only JSON expectations.

Please let me know if you need more info.

Thanks again for your awesome work. I appreciate it.

Regards,
Vins

**Comment by vin-vij** [comment]
if the watcherinitializationjson is set to false, the application works fine.

**Comment by jamesdbloom** [comment]
I'll take a look at this

**Comment by jamesdbloom** [comment]
When you update the file content for a file watcher MockServer replaces all expectations with the new contents of the file.  Perhaps this isn't clear enough from the documentation which I will fix.  

Is there a reason why you need both the class based initialiser and a file initialiser because that use cases isn't support when also using a file watcher.

**Comment by vin-vij** [comment]
hi James,

Thanks for the reply. 

The option to use both class based initializer and file initializer helps both static and dynamic (rule/input based) contents to be served easily.  We want to use the application such a way that, we can easily add new json files (external) and the logic in the code would pick the files based on the input. 
for example there will be an expectation in the java that will look for a file named response_abc.json when the request param/body contain  'abc', , and read response_xyz.json when request contains xyz

Hope this helps, please let me know if you need any further info.
Thanks for the great work.

Thanks,
Vins

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/Hn29Vk7C/152-maintain-class-expectation-initializer-expectations-when-also-using-json-expectation-initializer-and-file-watcher

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
