### ISSUE TITLE
Perform multiple actions on a given request

### ISSUE THREAD

**Issue by leozilla** [mock-server/mockserver#769]
**Describe the feature request**
I would like to perform 2 (or more) actions for a given request. My use case is that a specific HTTP request should return a HTTP response and trigger a callback to some other URL (after some delay).

**The solution you'd like**
It would be nice if its possible to setup the `Expectation` like this:
```
new Expectation(
        request().withMethod("POST").withPath("/api/v2/Payment/Secupaycreditcards"))
        .thenRespond(callback().withCallbackClass(PostPaymentSecupaycreditcardsHandler.class.getName()))
        .thenForward(callback().withCallbackClass(CallbackPaymentSecupaycreditcardsHandler.class.getName()).withDelay(5, TimeUnit.SECONDS))
```
But it seems this is not supported because there is explicit validation failing with `IllegalArgumentException`.

**Describe alternatives you've considered**
My current solution is to perform the HTTP callback myself in the `PostPaymentSecupaycreditcardsHandler` by using some HTTP client myself.

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/2PjaJecK/123-multiple-actions-per-expectation

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by jamesdbloom** [comment]
The reason the validation is in place for a single action is because MockServer only executes a single action per expectation, but I don't believe it should be too hard to support executing multiple actions, the major difficult in such an approach would be the complexity in the REST API to support multiple action and maintain backwards compatibility.

**Comment by afonsojorge15** [comment]
Is there any update on if multiple actions on a given request are now possible for Java MockServer?

**Comment by jamesdbloom** [comment]
This is now supported via #2180. You can set multiple action types on a single expectation using the `primary` flag:

```java
new Expectation(request().withMethod("POST").withPath("/api/v2/Payment"))
    .thenRespond(callback().withCallbackClass(PostPaymentHandler.class.getName()).withPrimary(true))
    .thenForward(callback().withCallbackClass(CallbackPaymentHandler.class.getName()).withDelay(5, TimeUnit.SECONDS))
```

Or use `afterActions` for post-action webhooks.
