### ISSUE TITLE
Clear the specific expectation with id

### ISSUE THREAD

**Issue by youngberg** [mock-server/mockserver#791]
**Describe the feature request**
Is it possible to have a client method to clear the specific expectation with id? I can only clear the expectations that match the given HttpRequest, but have matched more than I expected. 

**What you are trying to do**
Consider I have created such expectations and wanted to clear the second expectation only. In following code the mock server cleared the one with path '/hello/remote' as well as '/hello/*', which is not what I expected. 
```
MockServerClient mockClient = new MockServerClient("127.0.0.1",1080);

mockClient.when(request().withPath("/hello/.*")).respond(response().withBody("hello interface"));

mockClient.when(request().withPath("/hello/remote")).respond(response().withBody("hello remote"));

mockClient.clear(request().withPath("/hello/remote"), ALL);
```

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/2xAUJVNP/121-clear-by-expectation-id

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
