### ISSUE TITLE
Same response is returned for 2 differents requests

### ISSUE THREAD

**Issue by jmpdev34** [mock-server/mockserver#792]
**Expectations** :

- request 1 expectation on path and on 3 parameters -> response 1
- request 2 expectation on same path and on same 3 parameters and on 1 new  parameter -> response 2

The only difference is the new parameter for request 2, otherwise the requests are the same and same keys and values for parameters.

**Observation**
request 2 always returns response 1

**Workaround** 
Add Times.exactly(1) on requests expectation.

Version 5.5.4
TestContainers

**Comment by jamesdbloom** [comment]
This is expected behaviour because the matching is done in the order the expectations were added.  This is consistent with the majority the existing mocking frameworks such a Mockito, NMock, JMock, etc.

Please see: https://mock-server.com/mock_server/creating_expectations.html#matching_order

If you want the more specific expectation to be matched for more specific requests you need to add it first or give it a high priority as shown here: https://mock-server.com/mock_server/creating_expectations.html#button_match_request_by_priority
