### ISSUE TITLE
The ability to obtain a HAR file

### ISSUE THREAD

**Issue by StanislavSelen** [mock-server/mockserver#799]
**Describe the feature request**
Often, to analyze why the test fell, you need to analyze the requests and responses processed by the proxy server. It would be nice to be able to use the mock server to get the [HAR](https://en.wikipedia.org/wiki/HAR_(file_format)) file for further work with it in third-party programs.

**The solution you'd like**
Implement a method to save the HAR file. As an example [browserup-proxy](https://github.com/browserup/browserup-proxy):
`
Har har = proxy.getHar ();
`

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/ze09CJB1/124-create-har-file-from-proxied-requests

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
