### ISSUE TITLE
Support multiple initialization json files

### ISSUE THREAD

**Issue by heqiao** [mock-server/mockserver#808]
**Describe the feature request**
Be able to initialize multiple json files to better group the mocks and reduce the size of the initializerJson.json file.

**What you are trying to do**
I'm running a mock server docker container with initializerJson.json loading to it. We have a large application that interacts with 200+ third party API endpoints, and each request and response can be large (~50 lines),  and each API endpoint may have different scenarios, so we are talking about at least 10k+ lines of code in one file. 

**The solution you'd like**
Allow directory or multiple json files as the init data load.

**Describe alternatives you've considered**
N/A

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/y6QoKIWH/118-support-multiple-initialisation-json-files

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by jamesdbloom** [comment]
Closing issue as on backlog already

**Comment by heqiao** [comment]
Didn't mean to be pushy, just wonder if this is still shooting for next release as it has been in next release for a while.

**Comment by evbo** [comment]
Hi, does mockserver still plan to support this feature? Thanks for such a great library!
