### ISSUE TITLE
Add Windows-based Docker image for MockServer 

### ISSUE THREAD

**Issue by dmytro-pryvedeniuk** [mock-server/mockserver#820]
**Describe the feature request**
Add the official MockServer image for Windows-based containers. There are environments where Docker is running in Windows containers mode so the official Linux-based image does not work here.

**What you are trying to do**
Use MockServer in Windows containers Docker mode

**The solution you'd like**
Possible dockerfile
```
FROM winamd64/openjdk:11-jre-nanoserver-1809
COPY mockserver-netty-5.11.1-jar-with-dependencies.jar c:/
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-cp", "c:/mockserver-netty-5.11.1-jar-with-dependencies.jar", "-Dmockserver.propertyFile=/config/mockserver.properties", "org.mockserver.cli.Main"]
CMD ["-serverPort", "1080"]
```

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/4WzGuizA/154-add-windows-based-docker-image-for-mockserver

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
