### ISSUE TITLE
Nashhorn will be removed warning, please advice

### ISSUE THREAD

**Issue by vdotjansen** [mock-server/mockserver#833]
**Describe the issue**
We are using mockserver(-netty) in our testcases and when running the testcase with java 11 we get a warning
_Warning: Nashorn engine is planned to be removed from a future JDK release_
The Java warning warns because Nashhorn will be removed in Java 15: [JEP 372: Remove the Nashorn JavaScript Engine](http://openjdk.java.net/jeps/372)

**What you are trying to do**
We are trying to (integration) test if our code can connect to a external server to get data

**MockServer version**
5.5.1 (but upgrading did not help)

**To Reproduce**
Steps to reproduce the issue:

1. Create a testcase with a ClientAndServer class and start the server on @Before
2. Run the testcase in your IDE using Java 11 (or later)
3. See the warning on your screen

**Expected behaviour**
No JDK warning should be given. One of the solutions would be to provide a way to use another javascript engine in Java.

**MockServer Log**
_Warning: Nashorn engine is planned to be removed from a future JDK release_

**Comment by jamesdbloom** [comment]
It is not possible to remove this warning because it is output by the JsonSchema validation library which proactively loads the JS engine (which outputs this message to System.out) to support regex based JsonSchema, as the JDK regex libraries do not comply with JsonSchema regex rules.

Unfortunately there is nothing I can do to remove this warning except to re-implement an entire JsonSchema validation library.  I would like to do this however for potential performance reasons but the work required to transform radically different error messages from the validation is significant.  In addition alternative libraries are not as complete yet.

I'm am going to mark this as won't fix because there is no feasible practical way to solve this, although I'm open to PRs if someone has a way they feel it is possible to achieve.

**Comment by linkebon** [comment]
Will this give us problem when upgrading to java 15 or is this something that can be ignored?

**Comment by vdotjansen** [comment]
Maybe it is possible to fix this by depending on [rhino](https://github.com/mozilla/rhino) (as this is where nashorn came from, it is still maintained)?
They added a seperate jar for the script engine in the 1.7.13 release

**Comment by fhoner** [comment]
Can confirm that with openjdk15 templated response does not work any longer.
