### ISSUE TITLE
XmlSchemaBody matching requires local XSD for imported schemas

### ISSUE THREAD

**Issue by mikesaurus** [mock-server/mockserver#835]
The problem described in #534 still exists for use cases not addressed by the changes in the associated commit.

XmlSchemaValidator creates a Schema object using a String or Reader from the provided parent XSD:

```
            if (schema.trim().endsWith(">") || isBlank(schema)) {
                this.schema = schemaFactory.newSchema(new StreamSource(new StringReader(schema)));
            } else if (schema.trim().endsWith(".xsd")) {
                this.schema = schemaFactory.newSchema(new StreamSource(FileReader.openReaderToFileFromClassPathOrPath(schema)));
            }
```

This requires imported XSD to:
1. exist on the same filesystem where mockserver is running and, 
2. have a schemaLocation that is an absolute path or a path relative to the running process

Because the schema location cannot be relative to the parent XSD, schema files cannot be used in multiple contexts (such as in unit tests and after being mounted in a container volume) and XSD with imports cannot be loaded into mockserver from a remote file system using `request().withBody(xmlSchemaFromResource(schemaPath))`.

I have not tested this, but it may be possible to set an array of XSD Strings in the XmlSchemaBody using something like xmlSchemasFromPaths(Path... path) and then use the SchemaFactory.newSchema(Source[] schemas) method to create a Schema object in XmlSchemaValidator.

**Comment by jamesdbloom** [comment]
I agree that it could make sense to support an array of file locations

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/mdIrxV1q/155-xmlschemabody-matching-requires-local-xsd-for-imported-schemas

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
