### ISSUE TITLE
Support custom Body-implementations

### ISSUE THREAD

**Issue by Schubi1981** [mock-server/mockserver#879]
**Describe the feature request**
Add support for own implementations of org.mockserver.model.Body. Therefore it must also be possible to register an own implementation of  org.mockserver.serialization.model.BodyDto and org.mockserver.matchers.BodyMatcher in the org.mockserver.matchers.HttpRequestMatcher. With this feature, it would be possible to verify the body by any wanted logic. Maybe the body only has to contain a special word or has to start with a special prefix.

**What you are trying to do**
I'm trying to expect a specific JSON-Body in an IntegrationTest, but want to exclude some special fields from the comparison. These fields are timestamps and will differ each time the test is executed. We already have features to compare the JSON and exclude fields from this comparison and could wrap this own comparison in an own implementation of Body / BodyMatcher.

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/9SYkd4gb/64-custom-matchers

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
