### ISSUE TITLE
Streaming Endpoint Support

### ISSUE THREAD

**Issue by ewencluley** [mock-server/mockserver#886]
**Describe the feature request**
Ability to define an expectation for an endpoint that would provide a stream of data that could be manipulated at run time. E.g. a request to the endpoint would get a response with an open connection that, through client/api calls could have data added to it.

**What you are trying to do**
To write integration tests for some specific volume data http endpoints (e.g. Twitter volume streams) we need to simulate an http endpoint that acts as described above. We need to simulate these type of http endpoints that keep the connection open while real time data is streamed through the http response.

**The solution you'd like**
I guess it would require a way of describing an expectation with an open body and some sort of handle that can be written to. It maybe simplest to do this through the callback functionality by providing a response backed by an input stream that can be written to outside of the callback. Or to provide a `withBody` method that takes and InputStream and streams that as the response body. I'm not sure, I'm not overly familiar with the code

**Describe alternatives you've considered**
For now I have written a separate script that runs a web server that provides this functionality, however it would be great if this were part of the standard mock server offering.

**Comment by dszier** [comment]
I would add to this, the ability to proxy streaming endpoints.  Currently, if MockServer is set to forward a request to a remote server, and that remote maintains a long running chunked connection to send events over time (like a [server-sent events](https://en.wikipedia.org/wiki/Server-sent_events) endpoint), the connection to the MockServer will block and wait for the remote to close, rather than sending events back to the original requester as they come in.

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/9AULRsVY/156-streaming-endpoint-support

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
