### ISSUE TITLE
Allow verification of forwarded request's responses

### ISSUE THREAD

**Issue by charles-huet-ixxi** [mock-server/mockserver#898]
**Describe the feature request**
Allow to verify a response to a proxyed request.

**What you are trying to do**
I am using MockServer between a client and a server, and wish to verify that some requests are sent, and that the content of the responses match some expectations (e.g. statusCode)

I have proxyed my actual server with the following command in a JUnit5 test: 
`client.when(request()).forward(forwardOverriddenRequest(request().withHeader("Host", serverURL)));`

I do some verifications here and there, e.g. 
		client.verify(request().withPath("/api/security/setup")
				,request().withPath("/api/security/key")
				,request().withPath("/api/security/authenticate")
				);

**The solution you'd like**
I'd like to be able to do something like
```
client.verify(request().withPath("/api/security/setup")
 				,response().withStatusCode(200)
				,request().withPath("/api/security/key")
 				,response().withStatusCode(200)
				,request().withPath("/api/security/authenticate")
 				,response().withStatusCode(200)
				);
```
**Describe alternatives you've considered**
I have searched the issues and documentation, but did not find anything that matched this requirement.

Is there anything like it planned/already available and I failed to find it ?

Thanks

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/oXoiZBT3/157-allow-verification-of-forwarded-requests-responses

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
