### ISSUE TITLE
Regex body matcher does not match multiline body

### ISSUE THREAD

**Issue by tmonning-icw** [mock-server/mockserver#953]
**Describe the feature request**
Regex body matchers with wildcards do not match against the whole body string if it contains newline characters but the documentation does not mention that.

**What you are trying to do**
I was trying to use regex body matching in certain expectations for XML bodys and found out, that wildcard regexes didn't match. After having a look at the code I figured out, that regex matching uses Java's `Pattern.compile()` (see `NottableString#matches`) but without any flag. Therefore a request like the following:
```
<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
   <soapenv:Header/>
   <soapenv:Body>
      <ns:tag someAttribute="myValue" />
   </soapenv:Body>
</soapenv:Envelope>
```
wouldn't match this expectation injected by a json file:
```
[
  {
    "httpRequest": {
      "path": "/some/path",
      "body": {
        "type": "REGEX",
        "regex": ".*myValue.*"
      }
    },
    "httpResponse": {
      "statusCode": 200,
    }
  }
]
```
The match only succeeds when changing the regex to `(.|\\s)*myValue(.|\\s)*` which is a bit cumbersome and also error-prone.

**The solution you'd like**
I would like to have my regex with wildcards match against the whole body string ignoring newline characters. This could be achieved by using `Pattern.DOTALL` as a flag in the `Pattern.compile` call.

**Alternative solution**
Extend the documentation so it mentions that wildcard regexes do not match multiline bodies and include an example how to achieve the expected behavior.

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/MsZ1ctiq/177-regex-body-support-multiline-matching

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by jamesdbloom** [comment]
@tmonning-icw This is now implemented and the SNAPSHOT version to be released in the next few weeks.
