### ISSUE TITLE
Make pathParameters available to the template engines

### ISSUE THREAD

**Issue by boonen** [mock-server/mockserver#961]
**Describe the feature request**
Currently the different template engines have no direct access to the values of the `pathParameters` of an *Expectation* (see <https://github.com/mock-server/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/templates/engine/model/HttpRequestTemplateObject.java>). It would be nice to have simple access to the value of the defined path parameter. We can parse the *path* of a request and extract the value of the path parameter, but that can be quite tedious using JavaScript or Velocity.

**What you are trying to do**
I want the response of an Expectation to be dynamic, i.e. a path parameter value should be returned in the response. E.g.:

In the following request `/resources/{id}`, the value of `{id}` should be returned as:
```json
{
    "id": "{id}"
}
```

**The solution you'd like**
Ideally the value of path parameters should be added to the field `pathParameters` of the `HttpRequestTemplateObject`. The value can be parsed using the available matchers and then be made available to the template engine.

**Describe alternatives you've considered**
The only other option I see is to use String manipulation on the `path` property of the `HttpRequestTemplateObject`.

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/eFhJNDaL/176-make-pathparameters-available-to-the-template-engines

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by jamesdbloom** [comment]
This is now fixed in the latest SNAPSHOT version which will be released in the next few weeks.
