### ISSUE TITLE
Expose metrics

### ISSUE THREAD

**Issue by serg-bloim** [mock-server/mockserver#976]
**Describe the feature request**
Expose http metrics from the mockserver. 

**What you are trying to do**
I wanted to use mockserver in my performance test setup. One of the metrics I wanted to evaluate is a how much latency my app adds to the user's request. My app acts as a proxy between a user and mockserver. Thus I wanted to compare metrics like P99 from my app and from mockserver

**The solution you'd like**
It would be good to have an http endpoint with metrics, preferably in prometheus format such as:
- query count,
- response time distribution(prometheus histogram)

**Comment by tiarebalbi** [comment]
Bump this enhancement. Would be really good to have a specific endpoint to collect the current metrics, like number of requests and etc.

**Comment by jamesdbloom** [comment]
I agree that makes sense, there are already some metrics captured but these are not exposed.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/0D2dAV8g/159-expose-metrics

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by jamesdbloom** [comment]
@tiarebalbi I now have an initial implementation of a prothemeus format endpoint `/mockserver/metrics`, I had to use this format to reduce the chance of a collision with any expectation someone might want to set.  Once the build passes and I get back to my computer I'll push the commit.  This should be in the next release due in a couple of months or in the SNAPSHOT version in the next few days.

**Comment by tiarebalbi** [comment]
Thanks, @jamesdbloom, as soon as I see the snapshot version I'm going to give it a try.
